name: cb
services:
  - name: backend
    git:
      repo_clone_url: "https://github.com/codebuddies/backend.git"
      branch: staging-deployment-experiment
    run_command: gunicorn --worker-tmp-dir /opt/codebuddies/uwsgi.ini
    source_dir: project
    environment_slug: python
    envs:
    - key: DISABLE_COLLECTSTATIC
      value: "1"
      scope: BUILD_TIME
    - key: DJANGO_ALLOWED_HOSTS
      value: "${APP_DOMAIN}"
      scope: RUN_TIME
    - key: DATABASE_URL
      value: "${db.DATABASE_URL}"
      scope: RUN_TIME
databases:
- name: db
  engine: PG
  version: "12"
