name: cb
services:
  - name: backend
    git:
      repo_clone_url: "https://github.com/codebuddies/backend.git"
      branch: do_app_platform
    source_dir: project
    envs:
      - key: DISABLE_COLLECTSTATIC
        value: "1"
        scope: BUILD_TIME
      - key: DJANGO_ALLOWED_HOSTS
        value: "${APP_DOMAIN}"
        scope: RUN_TIME
      - key: DATABASE_URL
        value: "${db.DATABASE_URL}"
        scope: RUN_TIME
databases:
  - name: db
    engine: PG
    version: "12"
